### ISSUE TITLE
Translating page models from outside applications

### ISSUE THREAD

**Issue by SalahAdDin** [neon-jungle/wagtail-translations#6]
I'm trying adding translation feature for my project.

I have all page distributed in application, for get more order.

I tried add the initial configuration in the core application in models file:
models.py
```
from wagtailtranslations.models import AbstractTranslationIndexPage, TranslatedPage


class TranslationHomePage(AbstractTranslationIndexPage):
    subpage_types = ['HomePage', 'BlogPage']

```

But i'm getting this error:

```
./manage.py makemigrations                                                                                    1 ↵  5412  14:53:49 
SystemCheckError: System check identified some issues:

ERRORS:
?: (wagtailcore.E002) Invalid subpage_types setting for <class 'core.models.TranslationHomePage'>
        HINT: App 'home' doesn't have a 'blogpage' model.
```

So, i changed the file and i put in the home application, problem solved, but i need add other page to translatable page and i tried do the same with these models, in this case with blog page, getting the same error:
```
 salahaddin@TulipanROG  ~/Proyectos/uzman/uzman   internationalization ● ? ↑23  (uzman)  ./manage.py makemigrations                                                                                    1 ↵  5412  14:53:49 
SystemCheckError: System check identified some issues:

ERRORS:
?: (wagtailcore.E002) Invalid subpage_types setting for <class 'home.models.TranslationHomePage'>
        HINT: App 'home' doesn't have a 'blogpage' model.
 salahaddin@TulipanROG  ~/Proyectos/uzman/uzman   internationalization ● ? ↑23  (uzman)      
```

I have imported the model, of courese, but i'm getting the same error now:
models.py
```
from blog.models import BlogPage
```

Which is the correct workflow in this case?

**Comment by mx-moth** [comment]
`subpage_types` is documented in the Wagtail documentation: http://docs.wagtail.io/en/v1.9/reference/pages/model_reference.html?highlight=subpage_types#wagtail.wagtailcore.models.Page.subpage_types

In this case, you should use something like `subpage_types = ['home.HomePage', 'blog.BlogPage']`.

**Comment by SalahAdDin** [comment]
@timheap Yes, thank you!

This problem happen when i create a new migration in a project that have many other migrations, it means,  in already made problem. I didn't test it in a clean new project, so, i'm not sure if works fine in these case.
